server:
  port: 8769
http:
 eureka:
  serviceUrl: 127.0.0.1

eureka:
  instance:
     preferIpAddress: true
     metadataMap:
       instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    healthcheck:
      enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${http.eureka.serviceUrl}:8761/eureka/

spring:
  application:
    name: monitor
  boot:
    admin:
      url: http://localhost:${server.port}
  jackson:
    serialization:
      indent_output: true
  cloud:
    config:
      enabled: false


endpoints:
  health:
    sensitive: false

