spring:
 read:
   datasource:
     driverClassName: com.mysql.jdbc.Driver
     url: jdbc:mysql://localhost:3306/test_mysql?useUnicode=true&useSSL=false&characterEncoding=UTF-8
     username: root
     password: root

 write:
   datasource:
     driverClassName: com.mysql.jdbc.Driver
     url: jdbc:mysql://localhost:3306/test?useUnicode=true&useSSL=false&characterEncoding=UTF-8
     username: root
     password: root
 redis:
          host: localhost
          password:
          port: 6379
          database: 0
          pool:
              max-active: 8
              max-wait: -1
              max-idle: 20000
              min-idle: 0
          timeout: 10000
feign:
 client:
   url: 127.0.0.1:8283
springfox:
  name: spring cloud APi
  title: 权限资源管理在线文档
  description: 权限资源管理相关接口文档
