spring:
 read:
   datasource:
     driverClassName: com.mysql.jdbc.Driver
     url: jdbc:mysql://localhost:3306/test_mysql?useUnicode=true&characterEncoding=UTF-8
     username: root
     password: root

 write:
   datasource:
     driverClassName: com.mysql.jdbc.Driver
     url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8
     username: root
     password: root
springfox:
  name: spring cloud APi
  title: 用户管理在线文档
  description: 用户管理相关接口文档
