server:
  port: 8283

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

ribbon:
  eureka:
    enabled: true

springfox.documentation.swagger.v2.path: /api-docs



