server:
  port: 8761

eureka:
  instance:
    hostname: eurekaservicer
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eurekaservicer:${server.port}/eureka/

spring.cloud.config.discovery.enabled: true